version: '3.8'

services:
  postgres:
    container_name: pg_container
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aninotes
    ports:
      - 5432:5432
    volumes:
      - pg-data
    networks:
      - aninotes

  dpgamin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
    networks:
      - aninotes

volumes:
  pg-data:
    driver: local

networks:
  aninotes: